# Generated by Django 4.2 on 2024-07-08 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_payments_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='id_session',
            field=models.CharField(blank=True, help_text='Укажите id сессии', max_length=255, null=True, verbose_name='id сессии'),
        ),
        migrations.AddField(
            model_name='payments',
            name='link',
            field=models.URLField(blank=True, help_text='Укажите ссылку на оплату', max_length=400, null=True, verbose_name='ссылка на оплату'),
        ),
    ]
